const Counties = [
  'Albany',
  'Allegany',
  'Athlantic Ocean and Long Island Sound',
  'Bronx',
  'Broome',
  'Cattaraugus',
  'Cayuga',
  'Chautauqua',
  'Chemung',
  'Chenango',
  'Clinton',
  'Columbia',
  'Cortland',
  'Counties Unknown',
  'Delaware',
  'Dutchess',
  'Erie',
  'Essex',
  'Franklin',
  'Fulton',
  'Genesee',
  'Greene',
  'Hamilton',
  'Herikimer',
  'Jefferson',
  'Kings',
  'Lake Erie Open Waters',
  'Lake Ontario Open Waters',
  'Lewis',
  'Livingston',
  'Madison',
  'Monroe',
  'Montgomery',
  'Nassau',
  'New York',
  'Niagara',
  'Oneida',
  'Onondaga',
  'Ontario',
  'Orange',
  'Orleans',
  'Oswego',
  'Otsego',
  'Putnam',
  'Queens',
  'Rensselaer',
  'Richmond',
  'Rockland',
  'Saratoga',
  'Schenectady',
  'Schoharie',
  'Schuyler',
  'Seneca',
  'Steuben',
  'St. Lawrence',
  'Suffolk',
  'Sullivan',
  'Tioga',
  'Tompkins',
  'Ulster',
  'Warren',
  'Washington',
  'Wayne',
  'Westchester',
  'Wyoming',
  'Yates',
];
const Categories = ['Animal', 'Plant', 'Natural Community'];
const TaxonomicGroups = [
  'Amphibians',
  'Animal Assemblages',
  'Bees, Wasps and Ants',
  'Beetles',
  'Birds',
  'Butterflies and Moths',
  'Conifers',
  'Dragonflies and Damselflies',
  'Ferns and Fern Allies',
  'Fish',
  'Flies',
  'Flowering Plants',
  'Freshwater Nontidal Wetlands',
  'Lakes and Ponds',
  'Mammals',
  'Marine',
  'Mayflies',
  'Mosses',
  'Mussels and Clams',
  'Other Animals',
  'Reptiles',
  'Rivers and Streams',
  'Snails',
  'Stoneflies',
  'Subterranean',
  'Tidal Wetlands',
  'Uplands',
];

export { Counties, Categories, TaxonomicGroups };
