name: Node.js CI/CD to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to v4 for compatibility

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Updated to v4 for Node 20 compatibility
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install EB CLI
        run: pip install awsebcli --upgrade --user

      - name: Initialize EB CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          ~/.local/bin/eb init biodiversity-app --platform node.js --region $AWS_REGION
          ~/.local/bin/eb use Biodiversity-app-env-1

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          ~/.local/bin/eb deploy
